Combine datasets
Zymergen-DIRECT-2021/cytoxnet pull request #30
Opened 2021-06-05 21:25 UTC by roryjm

Lots of bug fixes.  Also added new example notebook for database loading.  Still need to add tests and example notebook for querying.

2021-06-06 07:35 UTC, EvanKomp approved these changes

2021-06-06 22:54 UTC, EvanKomp requested changes
We don't want to push csvs or database files created by the code, github isn't the place for that let the user do that with the code. 

What are the scripts in working? We are deleting that folder before submission. Are they the scripts created by your code? if so no need to include them. If they are hard coded and needed for the package, we would want to move them to cytoxnet

2021-06-07 02:17 UTC, EvanKomp approved these changes
csv files and sql should be removed I think?

2021-06-07 02:33 UTC, nidajanu approved these changes

2021-06-07 05:34 UTC, merged